version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: <your-root-password>
      MYSQL_USER: contact_keeper
      MYSQL_PASSWORD: <your-mysql-password>
      MYSQL_DATABASE: contact_keeper